# Generated by Django 2.0.6 on 2020-10-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hoddy',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
